name: Integration Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ADMIN_API_KEY: ${{ secrets.ADMIN_API_KEY }}
      REG_API_KEY: ${{ secrets.REG_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        env:
          PYTHONPATH: ./tests
        run: |
          python -m unittest tests.tests
